home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

vegetal:
    type:     rest
    resource: Arcamy\HomeBundle\Controller\RestController

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
